### ISSUE TITLE
Existing Pug templates fail compilation after upgrade to v0.9.0

### ISSUE THREAD

**Issue by rickclare** [rstacruz/exslim#11]
We are encountering multiple compilation errors when attempting to compile against **Expug v0.9.0** (this is with existing code that compiled successfully with **v0.8.0** and earlier).

We are using:
Erlang OTP-20.1.2
Elixir 1.5.2
phoenix 1.3.0
expug 0.9.0
phoenix_expug 0.1.1

Example compile failures are:

```
** (Expug.Error) lib/my_app_web/templates/error/401_unauthorized.html.pug: Parse error on line 19

            p If you are the application owner check the logs for more information.
             ^

Expug encountered a character it didn't expect.
```

```
** (Expug.Error) lib/my_app_web/templates/document/new.html.pug: Parse error on line 17

              em once
                ^

Expug encountered a character it didn't expect.
```

```
** (Expug.Error) lib/my_app_web/templates/layout/_app_footer.html.pug: Parse error on line 35

          em Contact:
            ^

Expug encountered a character it didn't expect.
```

```
** (Expug.Error) lib/my_app_web/templates/document/invalid.html.pug: Parse error on line 15

            li The document has been downloaded <em>previously</em>
              ^

Expug encountered a character it didn't expect.
```

```
** (Expug.Error) lib/my_app_web/templates/document/invalid.html.pug: Parse error on line 26

            li The document is no longer available
              ^

Expug encountered a character it didn't expect.

```

```
** (Expug.Error) lib/my_app_web/templates/error/401_unauthorized.html.pug: Parse error on line 14

            i.material-icons visibility_off
                            ^
Expug encountered a character it didn't expect.
```

```
** (Expug.Error) lib/my_app_web/templates/layout/_app_footer.html.pug: Parse error on line 14

          span |
              ^
Expug encountered a character it didn't expect.

```

**Comment by rickclare** [comment]
Note, the simple code example from https://github.com/rstacruz/expug/blob/master/README.md#expug also fails compilation for us.

i.e. the following code template:

```pug
doctype html
html
  meta(charset="utf-8")
  title Hello, world!
body
  a(href=@link)
    | This is a link
```

Fails to compile, giving the following error:

```
== Compilation error in file lib/my_app_web/views/layout_view.ex ==
** (Expug.Error) lib/my_app_web/templates/layout/app.pug: Parse error on line 4

      title Hello, world!
           ^

Expug encountered a character it didn't expect.

    lib/expug.ex:96: Expug.to_eex!/2
    lib/phoenix_expug/engine.ex:24: PhoenixExpug.Engine.read!/1
    lib/phoenix_expug/engine.ex:18: PhoenixExpug.Engine.compile/2
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:186: anonymous fn/3 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    lib/my_app_web/views/layout_view.ex:1: MyAppWeb.LayoutView (module)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by rickclare** [comment]
Looks like v0.9.2 has fixed this issue.  Thank you very much for fixing.
